In [ ]:
#imports
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset

In [ ]:
#file path collection
from google.colab import drive
drive.mount('/content/drive')

# Path to the main folder
main_folder = '/content/drive/My Drive/for_Andrei'

# List all files and subfolders in the main folder
files_list = []
unique_letters = set()
unique_letter_positions = []
for i, file_path in enumerate(os.listdir(main_folder)):
    if os.path.isfile(os.path.join(main_folder, file_path)):
      files_list.append(file_path)
      first_letter = file_path[0].lower()  # Convert to lowercase for case-insensitivity
      if first_letter not in unique_letters:
        unique_letters.add(first_letter)
        unique_letter_positions.append(i)



Mounted at /content/drive


In [ ]:
print(len(files_list))
print(len(unique_letters))
print(unique_letters)
print(unique_letter_positions)
unique_file_names = []
for position in unique_letter_positions:
  unique_file_names.append(files_list[position])
print(unique_file_names)


2361
4
{'h', 'n', 'f', 'l'}
[0, 998, 1000, 2000]
['H_523', 'lat', 'N_645', 'full_summary.csv']


In [ ]:
lat_name = 'lat'
lat_file_path = os.path.join(main_folder, lat_name)
full_summary_name = "full_summary.csv"
full_summary_path = os.path.join(main_folder, full_summary_name)
hydrogen_name = "H_"
hydrogen_file_path_list = []
nitrogen_name = "N_"
nitrogen_file_path_list = []

for file_name in files_list:
  if file_name.startswith(hydrogen_name):
    hydrogen_file_path_list.append(os.path.join(main_folder, file_name))
  if file_name.startswith(nitrogen_name):
    nitrogen_file_path_list.append(os.path.join(main_folder, file_name))

print(len(hydrogen_file_path_list))
print(len(nitrogen_file_path_list))


1179
1179


In [ ]:
temp_path = hydrogen_file_path_list[0]
with open(temp_path, 'r') as file:
  lines = file.readlines()
  print(lines)
  print(temp_path)
  lines = [float(number) for line in lines for number in line.strip().split()[:3]]
  print(lines)
  nested_lines = []
  for i in range(len(lines)):
    if i % 3 == 0:
      nested_lines.append(lines[i:i+3])
  print(nested_lines)
  array = np.array(nested_lines)
  print(array)

['   0.6250000000000000    0.1250000000000000    0.1250000000000000 \n', '   0.2499999999999999    0.2500000000000000    0.2499999999999999 \n', '   0.1250000000000001    0.1250000000000001    0.6250000000000000 \n', '   0.2499999999999999    0.7500000000000002    0.2499999999999999 \n', '   0.2499999999999999    0.2500000000000002    0.7499999999999999 \n', '   0.7499999999999999    0.2500000000000001    0.7499999999999999 \n', '   0.1250000000000002    0.6250000000000001    0.6249999999999999 \n', '   0.3750000000000003    0.3750000000000003    0.8749999999999999 \n', '   0.8750000000000001    0.8750000000000001    0.3750000000000001 \n']
/content/drive/My Drive/for_Andrei/H_523
[0.625, 0.125, 0.125, 0.2499999999999999, 0.25, 0.2499999999999999, 0.1250000000000001, 0.1250000000000001, 0.625, 0.2499999999999999, 0.7500000000000002, 0.2499999999999999, 0.2499999999999999, 0.2500000000000002, 0.7499999999999999, 0.7499999999999999, 0.2500000000000001, 0.7499999999999999, 0.1250000000000

In [ ]:
import time

start_time_1 = time.time()
main_data = {"Hydrogen": {}, "Nitrogen": {}}
for i, file_path in enumerate(hydrogen_file_path_list):
  with open(file_path, 'r') as file:
    path_name = os.path.basename(file_path)
    lines = file.readlines()
    lines = [float(number) for line in lines for number in line.strip().split()[:3]]
    nested_lines = []
    for i in range(0, len(lines), 3):
      try:
        nested_lines.append(lines[i:i+3])
      except IndexError:
        print(i)
        print(len(lines))
        print(f"Warning: Incomplete data in file {path_name}, skipping last line.")
    print(nested_lines)
    array = np.array(nested_lines)
    main_data["Hydrogen"][path_name] = array
end_time_1 = time.time()
print(end_time_1 - start_time_1)

start_time_2 = time.time()
for i, file_path in enumerate(nitrogen_file_path_list):
  with open(file_path, 'r') as file:
    path_name = os.path.basename(file_path)
    lines = file.readlines()
    lines = [float(number) for line in lines for number in line.strip().split()[:3]]
    nested_lines = []
    for i in range(0, len(lines), 3):
      try:
        nested_lines.append(lines[i:i+3])
      except IndexError:
        print(i)
        print(len(lines))
        print(f"Warning: Incomplete data in file {path_name}, skipping last line.")
    print(nested_lines)
    array = np.array(nested_lines)
    main_data["Nitrogen"][path_name] = array

print(main_data)
end_time_2 = time.time()
print(end_time_2 - start_time_2)

Streaming output truncated to the last 5000 lines.
       [0.75 , 0.25 , 0.25 ],
       [0.125, 0.625, 0.125],
       [0.125, 0.125, 0.625],
       [0.375, 0.375, 0.375],
       [0.625, 0.625, 0.125],
       [0.625, 0.125, 0.625],
       [0.875, 0.375, 0.375],
       [0.25 , 0.25 , 0.75 ],
       [0.75 , 0.25 , 0.75 ],
       [0.125, 0.625, 0.625],
       [0.375, 0.875, 0.375],
       [0.375, 0.375, 0.875],
       [0.625, 0.625, 0.625],
       [0.875, 0.875, 0.375],
       [0.875, 0.375, 0.875],
       [0.25 , 0.75 , 0.75 ],
       [0.75 , 0.75 , 0.75 ],
       [0.375, 0.875, 0.875],
       [0.875, 0.875, 0.875]]), 'H_1049': array([[0.375, 0.875, 0.875],
       [0.125, 0.625, 0.125]]), 'H_274': array([[0.125, 0.125, 0.125],
       [0.625, 0.125, 0.125],
       [0.75 , 0.25 , 0.25 ],
       [0.125, 0.625, 0.125],
       [0.125, 0.125, 0.625],
       [0.375, 0.375, 0.375],
       [0.625, 0.625, 0.125],
       [0.625, 0.125, 0.625],
       [0.875, 0.375, 0.375],
       [0.25 , 0.75 , 0.25

In [ ]:
print(main_data['Hydrogen']["H_1"])

[[0.125 0.125 0.125]
 [0.75  0.25  0.25 ]
 [0.125 0.625 0.125]
 [0.125 0.125 0.625]
 [0.75  0.75  0.25 ]
 [0.75  0.25  0.75 ]
 [0.125 0.625 0.625]
 [0.75  0.75  0.75 ]]


In [ ]:
import pickle

#save numpy array to drive
save_path_main = '/content/drive/My Drive/main_data.pkl'

with open(save_path_main, 'wb') as file:
  pickle.dump(main_data, file)



In [ ]:
#load numpy array from drive
with open(save_path_main, 'rb') as file:
  main_data = pickle.load(file)
print(main_data)

{'Hydrogen': {'H_523': array([[0.625, 0.125, 0.125],
       [0.25 , 0.25 , 0.25 ],
       [0.125, 0.125, 0.625],
       [0.25 , 0.75 , 0.25 ],
       [0.25 , 0.25 , 0.75 ],
       [0.75 , 0.25 , 0.75 ],
       [0.125, 0.625, 0.625],
       [0.375, 0.375, 0.875],
       [0.875, 0.875, 0.375]]), 'H_393': array([[0.625, 0.125, 0.125],
       [0.25 , 0.25 , 0.25 ],
       [0.75 , 0.25 , 0.25 ],
       [0.125, 0.625, 0.125],
       [0.125, 0.125, 0.625],
       [0.375, 0.375, 0.375],
       [0.625, 0.125, 0.625],
       [0.125, 0.625, 0.625],
       [0.375, 0.375, 0.875],
       [0.25 , 0.75 , 0.75 ],
       [0.375, 0.875, 0.875],
       [0.875, 0.875, 0.875]]), 'H_136': array([[0.25 , 0.25 , 0.25 ],
       [0.75 , 0.25 , 0.25 ],
       [0.375, 0.375, 0.375],
       [0.875, 0.375, 0.375],
       [0.25 , 0.25 , 0.75 ],
       [0.75 , 0.25 , 0.75 ],
       [0.375, 0.875, 0.375],
       [0.375, 0.375, 0.875],
       [0.875, 0.875, 0.375],
       [0.875, 0.375, 0.875],
       [0.375, 0.875, 0.8

In [ ]:
with open(lat_file_path, 'r') as file:
  lines = file.readlines()
  lines = [float(number) for line in lines for number in line.strip().split()[:3]]
  nested_lines = []
  for i in range(len(lines)):
    if i % 3 == 0:
      nested_lines.append(lines[i:i+3])
  lat_array = np.array(nested_lines)

save_path_lat = '/content/drive/My Drive/lat.pkl'
with open(save_path_lat, 'wb') as file:
  pickle.dump(array, file)
with open(save_path_lat, 'rb') as file:
  lat_data = pickle.load(file)
print(lat_data)

[[0.125 0.125 0.125]
 [0.25  0.75  0.25 ]
 [0.25  0.25  0.75 ]]


In [ ]:
full_summary_csv = pd.read_csv(full_summary_path)
save_path_full_summary = '/content/drive/My Drive/full_summary.pkl'
with open(save_path_full_summary, 'wb') as file:
  pickle.dump(full_summary_csv, file)
with open(save_path_full_summary, 'rb') as file:
  summary_data = pickle.load(file)
print(summary_data.head())

   Unnamed: 0 struct        comp      E_P0       V_P0     Vf_P0          B0  \
0           0  cf850   Lu8 H8 N8 -1.130328  14.094054 -2.655529    4.293235   
1           1  cf605   Lu8 N8 H7 -0.999093  11.364780 -5.825438  132.929108   
2           2  cf437   Lu8 N2 H4 -0.807152  16.686298 -3.807809   76.249128   
3           3  cf857   Lu8 N5 H5 -1.153465  11.788594 -6.980225  219.291495   
4           4  cf259  Lu8 H13 N6 -0.742638  10.097293 -4.922244   73.751054   

         BP0        c1s  Ncontent  Hcontent  
0  23.603981  -0.349457       8.0       8.0  
1  26.296966 -13.819227       8.0       7.0  
2   7.086653  -4.648556       2.0       4.0  
3  14.377721 -19.686839       5.0       5.0  
4   3.160800  -7.342995       6.0      13.0  


In [ ]:
energy_column = np.array(full_summary_csv['E_P0'])
energy_column_path = '/content/drive/My Drive/energy_column.pkl'
with open(energy_column_path, 'wb') as file:
  pickle.dump(energy_column, file)
with open(energy_column_path, 'rb') as file:
  energy_data = pickle.load(file)
print(energy_data)

[-1.13032754 -0.99909286 -0.80715201 ...  1.17897702 -0.30565406
  0.09494478]


In [ ]:
print(len(energy_data))
print(len(main_data['Hydrogen']))
print(len(main_data['Nitrogen']))
print(energy_data.size)
print(main_data['Hydrogen']['H_1'].size)
print(main_data['Nitrogen']['N_1'].size)
print(main_data['Hydrogen']['H_100'].size)
print(main_data['Nitrogen']['N_100'].size)

1179
1179
1179
1179
24
24
18
24


In [ ]:
repeated_lat_data = np.tile(lat_data, (1179, 1))
print(repeated_lat_data.shape)

(3537, 3)


In [ ]:
numpy_array = None
for key, value in main_data['Hydrogen'].items():
  print(key, value)

for key, value in main_data['Nitrogen'].items():
  print(key, value)


Streaming output truncated to the last 5000 lines.
H_780 [[0.125 0.625 0.125]
 [0.625 0.625 0.125]
 [0.625 0.125 0.625]
 [0.875 0.375 0.375]
 [0.25  0.25  0.75 ]
 [0.125 0.625 0.625]
 [0.375 0.875 0.375]
 [0.375 0.375 0.875]
 [0.875 0.875 0.375]
 [0.875 0.375 0.875]
 [0.25  0.75  0.75 ]
 [0.75  0.75  0.75 ]
 [0.875 0.875 0.875]]
H_729 [[0.125 0.125 0.125]
 [0.625 0.125 0.125]
 [0.25  0.25  0.25 ]
 [0.75  0.25  0.25 ]
 [0.125 0.625 0.125]
 [0.125 0.125 0.625]
 [0.375 0.375 0.375]
 [0.625 0.625 0.125]
 [0.625 0.125 0.625]
 [0.875 0.375 0.375]
 [0.25  0.75  0.25 ]
 [0.75  0.75  0.25 ]
 [0.75  0.25  0.75 ]
 [0.125 0.625 0.625]
 [0.375 0.875 0.375]
 [0.375 0.375 0.875]
 [0.625 0.625 0.625]
 [0.875 0.875 0.375]
 [0.875 0.375 0.875]
 [0.25  0.75  0.75 ]
 [0.375 0.875 0.875]
 [0.875 0.875 0.875]]
H_865 [[0.375 0.375 0.375]
 [0.25  0.75  0.75 ]
 [0.875 0.375 0.375]
 [0.375 0.375 0.875]
 [0.25  0.25  0.75 ]
 [0.75  0.25  0.75 ]
 [0.625 0.625 0.125]
 [0.75  0.75  0.25 ]
 [0.75  0.25  0.25 ]
 [0.6